 /* CREATE TABLE */
CREATE TABLE IF NOT EXISTS casos_COVID(
MUNICIPIO VARCHAR( 100 ),
CASOSENINVESTIGACION INT(11),
CASOSCONFIRMADOS INT(11),
CASOSRECUPERADOS INT(11),
DEFUNCIONES INT(11),
TRANSMISIONCOMUNITARIA INT(11)
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Abasolo',2,62,26,4,60
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Acámbaro',14,191,103,9,191
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Apaseo el Alto',13,66,27,6,66
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Apaseo el Grande',13,96,48,9,96
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Atarjea',0,2,0,0,2
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Celaya',137,1061,467,100,1051
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Comonfort',9,59,23,3,59
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Coroneo',1,29,18,0,28
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Cortazar',21,199,93,20,191
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Cuerámaro',7,77,44,1,77
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Doctor Mora',0,29,15,3,29
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Dolores Hidalgo',34,186,56,10,186
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Guanajuato',88,297,102,14,291
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Huanímaro',0,24,6,1,23
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Irapuato',180,1443,622,59,1433
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Jaral del Progreso',8,60,39,2,58
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Jerécuaro',2,62,37,2,61
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'León',1107,5666,2340,297,5628
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Manuel Doblado',1,28,12,1,28
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Moroleón',13,75,43,8,73
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Ocampo',3,32,8,2,32
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Pénjamo',21,203,86,11,198
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Pueblo Nuevo',0,30,21,0,30
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Purísima del Rincón',20,100,48,4,100
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Romita',18,402,312,23,401
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Salamanca',73,750,393,39,709
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Salvatierra',33,170,63,9,168
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'San Diego de la Unión',14,59,31,1,59
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'San Felipe',19,79,37,2,79
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'San Francisco del Rincón',21,308,111,11,307
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'San José Iturbide',7,81,27,4,81
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'San Luis de la Paz',21,181,88,13,179
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'San Miguel de Allende',17,137,65,9,133
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Santa Catarina',0,13,12,0,12
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Juventino Rosas',20,188,106,21,188
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Santiago Maravatio',1,30,24,3,29
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Silao',46,840,385,64,838
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Tarandacuao',2,25,12,2,24
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Tarimoro',4,43,20,1,42
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Tierra Blanca',0,27,20,1,26
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Uriangato',9,71,47,4,68
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Valle de Santiago',5,212,101,10,208
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Victoria',0,8,2,1,8
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Villagrán',15,93,39,8,92
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Xichú',0,7,6,1,7
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'Yuriria',4,52,24,3,50
);

/* INSERT QUERY */
INSERT INTO casos_COVID( MUNICIPIO,CASOSENINVESTIGACION,CASOSCONFIRMADOS,CASOSRECUPERADOS,DEFUNCIONES,TRANSMISIONCOMUNITARIA )
VALUES
(
	'No residente',13,2,0,0,0
);
